version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3336:3306"
    restart: always      
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  web:
    image: analisis2grupo3/g_3:latest
    build: .
    ports:
      - "3333:3333"
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  database:
    driver: "local"

  
    